Added mock liberata profile with active, deleted, on-hold
hmcts/ccpay-payment-app pull request #915
Opened 2021-05-24 14:17 UTC by vigneshpushkaranHMCTS

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-05-25 11:25 UTC, AyanDuttaHMCTS requested changes
Changes looks perfect, please refactor the minor comments

2021-05-25 11:25 UTC, AyanDuttaHMCTS commented on api/src/main/resources/application.properties
> +liberat.api.mock.account=pba0001_ACTIVE,pba0002_DELETED,pba0003_ON_HOLD
Can we have Accounts like PBA0001_ACTIVE

2021-05-25 11:25 UTC, AyanDuttaHMCTS commented on api/src/test/resources/application-componenttest.properties
> +liberata.api.mock = true
I think we need the PBA Account List here for functional test case

2021-05-25 11:25 UTC, AyanDuttaHMCTS commented on model/src/main/java/uk/gov/hmcts/payment/api/service/AccountServiceImpl.java
> +    private String accounts;
renaming accounts to 'mockPbaAccounts' will make more sense

2021-05-25 12:03 UTC, AyanDuttaHMCTS approved these changes
Changes looks good now.

2021-06-11 14:10 UTC, Jennings-HMCTS approved these changes

2022-11-02 17:35 UTC, closed without merging